spring.application.name=SmarttuneBackend
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/bd_smarttune?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.data.rest.base-path=/api

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# === MAILTRAP CONFIG ===
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=60098f0a1befb6
spring.mail.password=6832ccae73dfbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# === DEBUG EMAIL (voir les logs) ===
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# Configuration Email
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=rahmasassi2004@gmail.com
#spring.mail.password=yoqj yduh psxs ohtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration de l'application
app.frontend.url=http://localhost:8081

# Expiration du token de réinitialisation (15 minutes en millisecondes)
jwt.reset-password.expiration=900000



logging.level.org.springframework.web=DEBUG
logging.level.com.example.SmarttuneBackend=DEBUG
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
# Cloudinary
cloudinary.cloud-name=dqhou2ded
cloudinary.api-key=181394242527278
cloudinary.api-secret=KprszaQQrKpFcYNN6QOGBle5tvE